require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/*"
    - 'lib/task/*'

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/*"
    - 'lib/task/*'

Metrics/MethodLength:
  Max: 30

Rails/HttpPositionalArguments:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
