version: '2'
services:
  web:
    build: .
    command: bash -c 'bundle check || bundle install || bundle exec rspec spec'
    volumes:
      - solidus-mp-sync:/myapp:nocopy
volumes:
  solidus-mp-sync:
    external: true
